TAOS2:
    astig_tilty: -0.27600     # microns of astigmatism per mm of field per degree of tilt
    astig_transx: -0.00138    # microns of astigmatism per mm of field per mm of translation
    coma_tilty: 7.51748       # microns of coma per degree of tilt
    coma_transx: -1.10800     # microns of coma per mm of translation

    boxsize: 64
    
    defoc_scale: -0.2          # microns of zernike fringe focus per focus unit
    teldia: 1.3              # diameter of telescope in meters
    obscureratio: 0.5         # central obscuration ratio
    pix_size_arcsec: 0.6              # arcseconds per pixel
    pix_size_mm: 0.016      # mm per pixel
    center_pix_x: 4800
    center_pix_y: 4608
    fixed: [defoc_scale]
    max_field: 60
    
TAOS2-site3:
    astig_tilty: -0.27600     # microns of astigmatism per mm of field per degree of tilt
    astig_transx: -0.00138    # microns of astigmatism per mm of field per mm of translation
    coma_tilty: 7.51748       # microns of coma per degree of tilt
    coma_transx: -1.10800     # microns of coma per mm of translation

    boxsize: 64
    
    defoc_scale: -0.2          # microns of zernike fringe focus per focus unit
    teldia: 1.3              # diameter of telescope in meters
    obscureratio: 0.5         # central obscuration ratio
    pix_size_arcsec: 0.6              # arcseconds per pixel
    pix_size_mm: 0.016  # mm per pixel
    center_pix_x: 4800
    center_pix_y: 4608
    max_field: 60
    fixed:  [defoc_scale]
    
    